[project]
name = "mcq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "jinja2>=3.1.6",
]

[tool.uv.workspace]
members = [
    "mcq",
]
